# Copyright (c) 2019 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: import bf-sde-setup.yml
  import_playbook: bf-sde-setup.yml
  vars:
    install_dir: "{{ bf_sde_install_dir | default(ansible_facts['user_dir']) }}"

- hosts: all
  vars:
    install_dir: "{{ bf_sde_install_dir | default(ansible_facts['user_dir']) }}"
  tasks:
    - name: install bf-sde with P4 Runtime Profile
      command: >
        python $SDE/p4studio_build/p4studio_build.py
        --use-profile $SDE/p4studio_build/profiles/p4_runtime_profile.yaml
      environment:
        SDE: "{{ install_dir }}/bf-sde-{{ bf_sde_version }}"
        SDE_INSTALL: "{{ install_dir }}/bf-sde-{{ bf_sde_version }}/install"
      async: 10800
      poll: 15

    - name: Copy build python libs to runtime
      shell: >
        sudo cp -r
        /home/ubuntu/bf-sde-{{ bf_sde_version }}/install/lib/python2.7/site-packages/*
        /usr/local/lib/python2.7/dist-packages/