# Copyright (c) 2019 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
#Import playbook

- hosts: all
  gather_facts: no
  vars:
    - CENTOS_HOME: "/home/centos"
  tasks:
    - name: Install yum dependencies on AE CENTOS base image
      become: yes
      yum:
        name:
          - tcpdump
          - vim
          - wget
          - unzip
          - java-1.8.0-openjdk-devel
          - git
          - gcc
          - gcc-c++
          - bison
          - flex
          - libpcap-devel
          - qt-devel
          - gtk3-devel
          - rpm-build
          - libtool
          - c-ares-devel
          - qt5-qtbase-devel
          - qt5-qtmultimedia-devel
          - qt5-linguist
          - desktop-file-utils
          - openssl-devel
          - bzip2-devel
          - libffi-devel
          - libgcrypt-devel
          - ncurses-devel

    - name: Get Wireshark repository v3.2.6 tar to install Wireshark on AE CENTOS base image
      shell: wget https://www.wireshark.org/download/src/all-versions/wireshark-3.2.6.tar.xz
      args:
        chdir: /home/centos/

    - name: Untar Wireshark repository v3.2.6 to install Wireshark for AE image
      shell: "tar -xf {{CENTOS_HOME}}/wireshark-3.2.6.tar.xz"

    - name: Run rpm-setup script in Wireshark repository to install unmet dependencies for AE image
      become: yes
      shell: ./rpm-setup.sh -y
      args:
        chdir: /home/centos/wireshark-3.2.6/tools

    - name: Change Directory to home directory to install CMAKE v3.5.2 for AE image
      command: chdir=/home/centos ls

    - name: Get CMAKE repository using wget for AE images
      command: wget https://cmake.org/files/v3.5/cmake-3.5.2.tar.gz

    - name: Untar CMAKE repository
      shell: "tar -xf {{CENTOS_HOME}}/cmake-3.5.2.tar.gz"

    - name: Change directory to run CMAKE command for AE image
      command: chdir=/home/centos/cmake-3.5.2 ls

    - name: Bootstrap prefix usr before executing make for CMAKE installation on AE image
      become: yes
      shell: ./bootstrap --prefix=/usr
      args:
        chdir: /home/centos/cmake-3.5.2

    - name: Run make command for CMAKE installation for AE image
      become: yes
      shell: make install
      args:
        chdir: /home/centos/cmake-3.5.2


    - name: Verify CMAKE installed version on AE image
      become: yes
      command: cmake --version

    - name: Create build directory for Wireshark installation
      shell: mkdir build
      args:
        chdir: /home/centos

    - name: Run CMAKE command for wireshark installation for AE image
      become: yes
      shell: cmake ../wireshark-3.2.6
      args:
        chdir: /home/centos/build

    - name: Run MAKE command for wireshark installation for AE image
      become: yes
      shell: make
      args:
        chdir: /home/centos/build

    - name: Run INSTALL command for wireshark installation for AE image
      become: yes
      shell: make install
      args:
        chdir: /home/centos/build

    - name: Download and install a specific version of Python v3.8.5 for AE base image
      shell: curl -O https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz
      args:
        chdir: /home/centos

    - name: Untar Python directory
      shell: "tar -xf {{CENTOS_HOME}}/Python-3.8.5.tgz"


    - name: Configure Python optimizations for Python 3.8 install
      become: yes
      shell: ./configure --enable-optimizations;
      args:
        chdir: /home/centos/Python-3.8.5

    - name: Run INSTALL command for python 3.8 installation
      become: yes
      shell: make altinstall
      args:
        chdir: /home/centos/Python-3.8.5

    - name: Remove previously existing python3 configuration
      become: yes
      shell: rm -f /usr/bin/python3
      args:
        chdir: /home/centos

    - name: Reset Python3 version to Python3.8 installation
      become: yes
      shell: ln -s /usr/local/bin/python3.8 /usr/bin/python3
      args:
        chdir: /home/centos

    - name: Get repo OpenDistro Elasticsearch via RPM package
      become: yes
      shell: curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo
      args:
        chdir: /home/centos

    - name: Install OpenDistro Elasticsearch via RPM package
      become: yes
      shell: yum install opendistroforelasticsearch-1.11.0-1 -y
      args:
        chdir: /home/centos

    - name: Update links for OpenDistro Elasticsearch installation
      become: yes
      shell: ln -s /usr/lib/jvm/java-1.8.0/lib/tools.jar /usr/share/elasticsearch/lib/
      args:
        chdir: /home/centos

    - name: Remove opendistro_security plugin for current OpenDistro Elasticsearch installation
      become: yes
      shell:  bin/elasticsearch-plugin remove opendistro_security
      args:
        chdir: /usr/share/elasticsearch/

    - name: Install OpenDistro Elasticsearch Kibana via RPM
      become: yes
      shell: yum install opendistroforelasticsearch-kibana -y
      args:
        chdir: /home/centos

    - name: Update OpenDistro Elasticsearch Kibana config file
      become: yes
      copy:
        src: ./templates/opendistro_kibana.sh
        dest: /etc/kibana/kibana.yml
        force: yes


    - name: Copy TPS requirements.txt
      copy:
      src: ../../requirements.txt
      dest: ~/tps-py-requirements.txt

    - name: Install TPS Python requirements
      command: sudo pip3 install -r ~/tps-py-requirements.txt

