# Copyright (c) 2019 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Simple scenario where packets are sent through 3 devices and only the last
# one will be demonstrating dropped packets
---
# Sending 1 UDP packet expect 0 to be received
- import_playbook: test_cases/send_receive.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    receiver: host2
    reciever_log_filename: receiver-host2-1.out
    sender: host1
    sender_intf: "{{ host_sender_intf | default('host1-eth0') }}"
    sender_log_filename: sender-host1-1.out
    send_port: 4321
    send_src_port: 5432
    send_to_ip: "{{ topo_dict['hosts']['host2'].ip }}"
    send_packet_count: 1
    dst_switch_mac: "{{ switch.mac }}"
    min_received_packet_count: 0
    max_received_packet_count: 0

# Add table entry to data_forward_t
- import_playbook: test_cases/write_to_p4_table.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    grpc_addr: "{{ switch.grpc }}"
    switch_id: "{{ switch.id }}"
    te_conf_file: ~/te-df-host2-forward-1.yml
    p4_ingress_classname: TpsGwIngress
    p4_table_name: data_forward_t
    p4_action_name: data_forward
    p4_table_match_fields:
      - key: standard_metadata.ingress_port
        value: 1
    p4_table_action_params:
      - key: dstAddr
        value: "{{ topo_dict['hosts']['host2'].mac }}"
      - key: port
        value: 2
      - key: l2ptr
        value: 0
    p4_info_fpath: "{{ switch.runtime_p4info }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: te-df-host2-forward-1.log

# Sending 1 UDP packet expect 1 to be received
- import_playbook: test_cases/send_receive.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    receiver: host2
    reciever_log_filename: receiver-host2-2.out
    sender: host1
    sender_intf: "{{ host_sender_intf | default('host1-eth0') }}"
    sender_log_filename: sender-host1-2.out
    send_port: 4321
    send_src_port: 5432
    send_to_ip: "{{ topo_dict['hosts']['host2'].ip }}"
    send_packet_count: 1
    dst_switch_mac: "{{ switch.mac }}"

# Delete table entry to data_forward_t
- import_playbook: test_cases/write_to_p4_table.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    grpc_addr: "{{ switch.grpc }}"
    switch_id: "{{ switch.id }}"
    te_conf_file: ~/te-df-host2-forward-delete-1.yml
    p4_ingress_classname: TpsGwIngress
    p4_table_name: data_forward_t
    p4_table_match_fields:
      - key: standard_metadata.ingress_port
        value: 1
    p4_info_fpath: "{{ switch.runtime_p4info }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: te-df-host2-forward-revert.log
    p4_te_insert: False

# Sending 1 UDP packet expect 0 to be received
- import_playbook: test_cases/send_receive.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    receiver: host2
    reciever_log_filename: receiver-host2-3.out
    sender: host1
    sender_intf: "{{ host_sender_intf | default('host1-eth0') }}"
    sender_log_filename: sender-host1-3.out
    send_port: 4321
    send_src_port: 5432
    send_to_ip: "{{ topo_dict['hosts']['host2'].ip }}"
    send_packet_count: 1
    dst_switch_mac: "{{ switch.mac }}"
    min_received_packet_count: 0
    max_received_packet_count: 0

# Add back table entry to data_forward_t
- import_playbook: test_cases/write_to_p4_table.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    grpc_addr: "{{ switch.grpc }}"
    switch_id: "{{ switch.id }}"
    te_conf_file: ~/te-df-host2-forward-2.yml
    p4_ingress_classname: TpsGwIngress
    p4_table_name: data_forward_t
    p4_action_name: data_forward
    p4_table_match_fields:
      - key: standard_metadata.ingress_port
        value: 1
    p4_table_action_params:
      - key: dstAddr
        value: "{{ topo_dict['hosts']['host2'].mac }}"
      - key: port
        value: 2
      - key: l2ptr
        value: 0
    p4_info_fpath: "{{ switch.runtime_p4info }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: te-df-host2-forward-2.log

# Sending 1 UDP packet expect 1 to be received
- import_playbook: test_cases/send_receive.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    receiver: host2
    reciever_log_filename: receiver-host2-4.out
    sender: host1
    sender_intf: "{{ host_sender_intf | default('host1-eth0') }}"
    sender_log_filename: sender-host1-4.out
    send_port: 4321
    send_src_port: 5432
    send_to_ip: "{{ topo_dict['hosts']['host2'].ip }}"
    send_packet_count: 1
    dst_switch_mac: "{{ switch.mac }}"

# Add table entry to data_inspect_t
- import_playbook: test_cases/write_to_p4_table.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    host: "{{ topo_dict['hosts']['host2'] }}"
    grpc_addr: "{{ switch.grpc }}"
    switch_id: "{{ switch.id }}"
    te_conf_file: ~/te-inspect-host2.yml
    p4_ingress_classname: TpsGwIngress
    p4_table_name: data_inspection_t
    p4_action_name: data_inspect_packet
    p4_table_match_fields:
      - key: hdr.ethernet.src_mac
        value: "{{ host.mac }}"
    p4_table_action_params:
      - key: device
        value: "{{ host.id }}"
      - key: switch_id
        value: "{{ switch.id }}"
    p4_info_fpath: "{{ switch.runtime_p4info }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: te-inspect-host2.log

# Sending 1 UDP packet expect 1 to be received
- import_playbook: test_cases/send_receive.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    receiver: host2
    reciever_log_filename: receiver-host2-5.out
    sender: host1
    sender_intf: "{{ host_sender_intf | default('host1-eth0') }}"
    sender_log_filename: sender-host1-5.out
    send_port: 4321
    send_src_port: 5432
    send_to_ip: "{{ topo_dict['hosts']['host2'].ip }}"
    send_packet_count: 1
    dst_switch_mac: "{{ switch.mac }}"

# Delete table entry to data_forward_t
- import_playbook: test_cases/write_to_p4_table.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    grpc_addr: "{{ switch.grpc }}"
    switch_id: "{{ switch.id }}"
    te_conf_file: ~/te-df-host2-forward-2-delete.yml
    p4_ingress_classname: TpsGwIngress
    p4_table_name: data_forward_t
    p4_table_match_fields:
      - key: standard_metadata.ingress_port
        value: 1
    p4_info_fpath: "{{ switch.runtime_p4info }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: te-df-host2-forward-revert.log
    p4_te_insert: False

# Delete table entry to data_inspect_t
- import_playbook: test_cases/write_to_p4_table.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    host: "{{ topo_dict['hosts']['host2'] }}"
    grpc_addr: "{{ switch.grpc }}"
    switch_id: "{{ switch.id }}"
    te_conf_file: ~/te-inspect-host2-delete.yml
    p4_ingress_classname: TpsGwIngress
    p4_table_name: data_inspection_t
    p4_table_match_fields:
      - key: hdr.ethernet.src_mac
        value: "{{ host.mac }}"
    p4_info_fpath: "{{ switch.runtime_p4info }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: te-inspect-host2-delete.log
    p4_te_insert: False

# Sending 1 UDP packet expect 0 to be received
- import_playbook: test_cases/send_receive.yml
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch: "{{ topo_dict['switches']['gateway'] }}"
    receiver: host2
    reciever_log_filename: receiver-host2-6.out
    sender: host1
    sender_intf: "{{ host_sender_intf | default('host1-eth0') }}"
    sender_log_filename: sender-host1-6.out
    send_port: 4321
    send_src_port: 5432
    send_to_ip: "{{ topo_dict['hosts']['host2'].ip }}"
    send_packet_count: 1
    dst_switch_mac: "{{ switch.mac }}"
    min_received_packet_count: 0
    max_received_packet_count: 0
