# Copyright (c) 2019 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: install dependecies
  apt:
    name:
      - bridge-utils

- name: extract data
  set_fact:
    this_host: "{{ topo_dict.hosts.get(ansible_host) }}"
    remote_host: "{{ topo_dict.hosts.get(item.host) }}"
    virt_intf: "{{ item.virt_intf }}"
    br_name: "{{ item.bridge_name | default('br0') }}"
    tun_name: "{{ item.tunnel_name | default('gre-tun0') }}"

- name: set this_host from switches when not in hosts
  set_fact:
    this_host: "{{ topo_dict.switches.get(ansible_host) }}"
  when: not this_host

- name: set remote_host from switches when not in hosts
  set_fact:
    remote_host: "{{ topo_dict.switches.get(item.host)  }}"
  when: not remote_host

- name: retrieve host_ip, remote_ip, and virt_intf values
  set_fact:
    host_ip: "{{ this_host.ip }}"
    remote_ip: "{{ remote_host.ip }}"

- name: create virtual nic {{ virt_intf }}
  command: "ifconfig {{ virt_intf }}"
  when: host_type == 'host'

- name: create connection from {{ tun_name }} to {{ remote_ip }} on host {{ host_ip }}
  command: "ip link add {{ tun_name }} type gretap remote {{ remote_ip }} local {{ host_ip }} ttl 32"

- name: create bridge {{ br_name }}
  command: "brctl addbr {{ br_name }} {{ host_ip }}"

# TODO - determine why adding the bridge to the virtual interface is causing networking to fail
#- name: create port {{ br_name }} -> {{ virt_intf }}
#  command: "brctl addif {{ br_name }} {{ virt_intf }}"

- name: create port {{ br_name }} -> {{ tun_name }}
  command: "brctl addif {{ br_name }} {{ tun_name }}"

- name: set bridge up
  command: "ip link set {{ br_name }} up"

- name: set gre tunnel up
  command: "ip link set {{ tun_name }} up"

- name: set {{ virt_intf }} up
  command: "ip link set {{ virt_intf }} up"

- name: set bridge stp on
  command: "brctl stp {{ br_name }} on"
