# Copyright (c) 2019 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# see https://community.hetzner.com/tutorials/linux-setup-gre-tunnel
---
- name: delete bridge {{ item.bridge_name }}
  command: "brctl delbr {{ item.bridge_name }}"
  ignore_errors: yes

- name: create bridge {{ item.bridge_name }} to {{ this_host.ip }}
  command: "brctl addbr {{ item.bridge_name }}"

- name: create port {{ item.bridge_name }} -> {{ item.tunnel_name }}
  command: "brctl addif {{ item.bridge_name }} {{ item.tunnel_name }}"

# TODO - determine why adding the bridge to the virtual interface is causing networking to fail
- name: create port {{ item.bridge_name }} -> {{ item.virt_intf }}
  command: "brctl addif {{ item.bridge_name }} {{ item.virt_intf }}"

- name: set bridge up - {{ item.bridge_name }}
  command: "ip link set {{ item.bridge_name }} up"
