# Copyright (c) 2019 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Ensure {{ remote_scripts_dir }} directory has been created
  become: yes
  file:
    path: "{{ remote_scripts_dir }}/p4"
    state: directory

- set_fact:
    compile_switch: "{{ topo_dict.switches[switch_name] }}"

- name: Determine P4 program name and base compile command when arch == 'v1model'
  set_fact:
    p4_program_name: "{{ p4_prog }}"
  when: compile_switch.arch is not defined or compile_switch.arch == 'v1model'

- name: Determine P4 program name and base compile command when arch != 'v1model'
  set_fact:
    p4_program_name: "{{ p4_prog }}_{{ compile_switch.arch }}"
  when: compile_switch.arch is defined and compile_switch.arch != 'v1model'

- name: Populate compile variables/facts
  set_fact:
    sde_target_dir: "$SDE_INSTALL/share/p4/targets/tofino/{{ p4_prog }}"
    build_obj_dir: "{{ remote_scripts_dir }}/p4/{{ p4_prog }}.tofino"
    build_prog: "{{ trans_sec_dir }}/p4/{{ p4_prog }}/{{ p4_program_name }}.p4"

- name: Determine P4 program name and base compile command when arch == 'v1model'
  set_fact:
    compile_command: >
      {{ compile_command }} --p4runtime-format text --arch v1model -D TOFINO
      --p4runtime-files {{ remote_scripts_dir }}/p4/{{ p4_prog }}.tofino/p4info.pb.txt
  when: compile_switch.arch is not defined or compile_switch.arch == 'v1model'

- name: Determine P4 program name and base compile command when arch != 'v1model'
  set_fact:
    compile_command: "{{ compile_command }} --arch {{ compile_switch.arch }} -D TOFINO_{{ compile_switch.arch }}"
  when: compile_switch.arch is defined and compile_switch.arch != 'v1model'

- name: Create directory {{ artifact_path }}
  file:
    path: "{{ sde_target_dir }}"
    state: directory

- name: Complete building the compile command
  set_fact:
    compile_command: >
      {{ compile_command }}
      --bf-rt-schema {{ build_obj_dir }}/bf-rt.json
      -o {{ build_obj_dir }}
      {{ build_prog }}

- name: The actual compile command to be executed
  debug:
    var: compile_command

- name: Compile P4 program
  become: yes
  command: "{{ compile_command }}"
  args:
    chdir: "{{ remote_scripts_dir }}"

- name: Copy compiled *.conf file to {{ sde_p4_target_dir }}
  copy:
    src: "{{ build_obj_dir }}/{{ p4_program_name }}.conf"
    dest: "{{ sde_p4_target_dir }}/{{ p4_prog }}.conf"
    remote_src: yes
