# Copyright (c) 2019 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Copy TPS source from orchestrator to all switches
- import_playbook: ../general/setup_source.yml
  vars:
    host_val: "{{ switches }}"
    trans_sec_source_dir: "{{ orch_trans_sec_dir }}"
    python_unit_tests: false
    install_tps_python: false

# Compile the proper P4 program on the switch
- import_playbook: compile_p4.yml
  vars:
    host_val: "{{ switches }}"

# Start tofino model chip emulator
- import_playbook: ../general/start_service.yml
  vars:
    host_val: "{{ switches }}"
    service_name: tps-tofino-model
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    the_switch: "{{ topo_dict.switches[switch_name] }}"
    tunnels: "{{ the_switch.tunnels }}"
    local_srvc_script_tmplt_file: "{{ trans_sec_dir }}/playbooks/general/templates/tofino_service.sh.j2"
    port_to_wait: "{{ tofino_model_port }}"
    prog_name: "{{ p4_prog }}"
    additional_tmplt_file: "{{ trans_sec_dir }}/playbooks/tofino/templates/tofino-model-veth-port-mapping.json.j2"
    additional_tmplt_out_file: "{{ remote_scripts_dir }}/port-mapping.json"
  when: not from_hw | bool

# Start switchd
- import_playbook: ../general/start_service.yml
  vars:
    host_val: "{{ switches }}"
    service_name: tps-tofino-switchd
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    switch_arch: "{{ topo_dict.switches[switch_name].arch }}"
    tmplt_dir: "{{ trans_sec_dir }}/playbooks/tofino/templates"
    local_srvc_script_tmplt_file: ../tofino/templates/switchd_service.sh.j2
    port_to_wait: "{{ grpc_port }}"
    wait_timeout: 90
    prog_name: "{{ p4_prog }}"
    srvc_start_pause_time: 30
    log_file: "{{ log_dir }}/tofino-switchd.log"
    # TODO/FIXME - Fix the status of the service
    service_status_running: false

# Load P4-RT
- import_playbook: ../general/start_service.yml
  vars:
    host_val: "{{ switches }}"
    service_name: tps-tofino-load-p4rt
    local_srvc_script_tmplt_file: "{{ trans_sec_dir }}/playbooks/general/templates/tofino_p4rt_service.sh.j2"
    prog_name: "{{ p4_prog }}"
    srvc_start_pause_time: 15
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    start_service: "{% if topo_dict.switches[switch_name].arch == 'v1model' %}True{% else %}False{% endif %}"
