# Copyright (c) 2019 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Simple scenario where packets are sent through 3 devices and only the last
# one will be demonstrating dropped packets
---
# Add table entry to "{{ data_forward_table }}"
- import_playbook: ../test_cases/write_to_p4_table.yml
  vars:
    te_conf_file: "~/di-forward-create-{{ send_protocol }}.yml"
    p4_classname: "{{ ingress_classname }}"
    p4_table_name: "{{ data_forward_table }}"
    p4_action_name: "{{ data_forward_action }}"
    p4_table_match_fields: "{{ data_forward_match_fields }}"
    p4_table_action_params: "{{ data_forward_action_params }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: "di-forward-create-{{ send_protocol }}.log"

# Add table entry to "{{ data_inspection_table }}"
- import_playbook: ../test_cases/write_to_p4_table.yml
  vars:
    te_conf_file: "~/di-inspect-create-{{ send_protocol }}.yml"
    p4_classname: "{{ ingress_classname }}"
    p4_table_name: "{{ data_inspection_table }}"
    p4_action_name: "{{ data_inspection_action }}"
    p4_table_match_fields: "{{ data_inspection_match_fields }}"
    p4_table_action_params: "{{ data_inspection_action_params }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: "di-inspection-create-{{ send_protocol }}.log"

# Sending UDP packets expect all to be received with one INT hop
- import_playbook: ../test_cases/send_receive.yml
  vars:
    receiver_log_filename: "di_basic_receiver-{{ send_protocol }}-1.out"
    sender_log_filename: "di_basic_sender-{{ send_protocol }}-1.out"
    send_port: "{{ range(2000, 10000) | random(seed='one') }}"
    send_src_port: "{{ range(2000, 10000) | random(seed='two') }}"
    send_packet_count: "{{ 100 | random(seed='three') }}"
    inspection_data: "{{ sr1_data_inspection_int | default(None) }}"
    int_hops: "{{ sr1_rec_int_hops | default(0) }}"

# Delete table entry to "{{ data_inspection_table }}"
- import_playbook: ../test_cases/write_to_p4_table.yml
  vars:
    te_conf_file: "~/di-inspect-delete-{{ send_protocol }}.yml"
    p4_classname: "{{ ingress_classname }}"
    p4_table_name: "{{ data_inspection_table }}"
    p4_table_match_fields: "{{ data_inspection_match_fields }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: "di-inspection-delete-{{ send_protocol }}.log"
    p4_te_insert: False

# Sending UDP packet expect to be received without INT
- import_playbook: ../test_cases/send_receive.yml
  vars:
    receiver_log_filename: "di_basic_receiver-{{ send_protocol }}-2.out"
    sender_log_filename: "di_basic_sender-{{ send_protocol }}-2.out"
    send_port: "{{ range(2000, 10000) | random(seed='two') }}"
    send_src_port: "{{ range(2000, 10000) | random(seed='three') }}"
    send_packet_count: "{{ 100 | random(seed='four') }}"
    inspection_data: "{{ sr2_data_inspection_int | default(None) }}"
    int_hops: "{{ sr2_rec_int_hops | default(0) }}"

# Delete table entry to "{{ data_forward_table }}"
- import_playbook: ../test_cases/write_to_p4_table.yml
  vars:
    te_conf_file: "~/di-forward-delete-{{ send_protocol }}.yml"
    p4_classname: "{{ ingress_classname }}"
    p4_table_name: "{{ data_forward_table }}"
    p4_table_match_fields: "{{ data_forward_match_fields }}"
    p4_te_log_dir: "{{ host_log_dir }}"
    p4_te_log_file: "di-forward-delete-{{ send_protocol }}.log"
    p4_te_insert: False

# Sending UDP packet expect none to be received
- import_playbook: ../test_cases/send_receive.yml
  vars:
    receiver_log_filename: "di_basic_receiver-{{ send_protocol }}-3.out"
    sender_log_filename: "di_basic_sender-{{ send_protocol }}-3.out"
    send_port: "{{ range(2000, 10000) | random(seed='two') }}"
    send_src_port: "{{ range(2000, 10000) | random(seed='three') }}"
    send_packet_count: "{{ 100 | random(seed='four') }}"
    inspection_data: "{{ sr3_data_inspection_int | default(None) }}"
    int_hops: "{{ sr3_rec_int_hops | default(0) }}"
    min_received_packet_count: 0
    max_received_packet_count: 0
