# Copyright (c) 2020 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Simple scenario where packets are sent through 3 devices and only the last
# one will be demonstrating dropped packets
---
# Call POST on all WS calls
- hosts: controller
  gather_facts: no
  vars:
    topo_dict: "{{ lookup('file','{{ topo_file_loc }}') | from_yaml }}"
    aggregate: "{{ topo_dict.switches.aggregate }}"
    core: "{{ topo_dict.switches.core }}"
    host1: "{{ topo_dict.hosts.host1 }}"
    inet: "{{ topo_dict.hosts.inet }}"
    ae: "{{ topo_dict.hosts.ae }}"
    ws_calls:
      - url: "http://{{ sdn_ip }}:{{ sdn_port }}/setupTelemRpt"
        body:
          device_id: "{{ core.id }}"
          switch_mac: "{{ core.mac }}"
          port: 555
          ae_ip: "{{ ae_ip }}"
          ae_mac: "{{ ae.mac }}"
        ok_status: 201
      - url: "http://{{ sdn_ip }}:{{ sdn_port }}/dataInspection"
        body:
          device_id: "{{ aggregate.id }}"
          switch_mac: "{{ aggregate.mac }}"
          device_mac: "{{ host1.mac }}"
        ok_status: 201
  tasks:
    - name: Web service calls to make
      debug:
        var: ws_calls

    - name: POST WS calls
      uri:
        url: "{{ item.url }}"
        method: POST
        body_format: "{{ item.body_format | default('json') }}"
        body: "{{ item.body }}"
        status_code: "{{ item.ok_status | default('200') }}"
      with_items: "{{ ws_calls }}"
