# Copyright (c) 2020 Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Simple scenario where packets are sent through 3 devices and only the last
# one will be demonstrating dropped packets
---
# Restart Switches to clear all and start fresh
- hosts:
    - aggregate
    - core
  gather_facts: no
  become: yes
  vars:
    restart_switch: "{{ switch_restart | default(True) }}"
    run_on_hw: "{{ from_hw | default(False) | bool }}"
    restart_model: "{{ not run_on_hw|bool }}"
  tasks:
    - block:
      - name: Stop tps-tofino-switchd
        systemd:
          name: tps-tofino-switchd
          state: stopped

      - name: Restart tps-tofino-model
        systemd:
          name: tps-tofino-model
          state: restarted
        when: restart_model

      - name: Restart tps-tofino-switchd
        systemd:
          name: tps-tofino-switchd
          state: restarted
      when: restart_switch

    - name: Wait for tps-tofino-switchd to open port
      wait_for:
        port: "{{ switchd_port | default(50052) }}"
        timeout: 90

# Restart SDN service to ensure P4 tables are properly setup for the next set of tests
- hosts: controller
  gather_facts: no
  become: yes
  tasks:
    - name: Restart tps-tofino-sdn
      systemd:
        name: tps-tofino-sdn
        state: restarted

    - name: Wait for tps-tofino-sdn to open port
      wait_for:
        port: "{{ sdn_port | default(9998) }}"
        timeout: 60

# Manage AE service (restart to ensure moving window gets reset)
- hosts: ae
  gather_facts: no
  become: yes
  vars:
    ae_srvc_state: "{{ ae_state | default('stopped') }}"
    es_pcap_state: "{{ es_pcap_srvc_state | default('stopped') }}"
    exe_systemd: "{% if ae_srvc_state == 'none' %}False{% else %}True{% endif %}"
  tasks:
    - debug:
        var: exe_systemd
    - name: Restart tps-tofino-ae with state {{ ae_srvc_state }}
      systemd:
        name: tps-tofino-ae
        state: "{{ ae_srvc_state }}"
      when: exe_systemd | bool

# This is required for snaps-hcp
#    - name: Restart tps-es-pcap with state {{ es_pcap_state }}
#      systemd:
#        name: tps-es-pcap
#        state: "{{ ae_srvc_state }}"
#      when: exe_systemd | bool
